name: frontend-master workflow

on: 
  push:
    branches:
      - dev-L00171125-Abhishek-DGW-132
  pull_request:
    types:
      - "opened"
jobs:
  Build_docker_FrontendImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Sign in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}} 
      - name: Deleting old Images 
        run: docker rmi -f $(docker images -q)
      - name: Build Docker Frontend Images
        run: |
         cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-frontend-master
         docker build -t wwag3/wednesdaywickedadventures/fronted:latest . 
      - name: Build Docker Backend Images
        run: |
         cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-backend-master
         docker build -t wwag3/wednesdaywickedadventures/backend:latest . 
      - name: Publish Image to docker Hub
        run: docker push wwag3/wednesdaywickedadventures:latest

  Pulling_docker_image:
    runs-on: self-hosted
    needs: Build_docker_FrontendImage
    steps:
      - name: pulling image from docker hub 
        run: sudo docker pull wwag3/wednesdaywickedadventures:latest

      - name: Deleting old contanier 
        run: sudo docker rm -f wwafrontendapp

      - name: building container
        run: sudo docker run --name wwafrontendapp -p 3000:3000 -d  wwag3/wednesdaywickedadventures:latest

      - name: Deleting old contanier 
        run: sudo docker rm -f wwabackend

    #  - name: building docker backend
    #    run: sudo docker run --name wwabackend -p 5000:5000 -d pavanvarikolu/wwabackend:v1.1.1




   