name: frontend-master workflow

on: 
  push:
    branches:
      - dev-L00171125-Abhishek-DGW-132
  pull_request:
    types:
      - "opened"
jobs:
  WWA-backend-master:
     runs-on: ubuntu-latest
     steps:
      - name: getting code
        uses: actions/checkout@v4
      - name: installing nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: running code
        run: |
          cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-backend-master
          sudo npm i
          sudo npm run test  

  WWA-frontend-master:
   # needs: Running_backend
    runs-on: ubuntu-latest
    steps:
      - name: getting code
        uses: actions/checkout@v4
      - name: installing nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: installing  dependencies
        run: |
          cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-frontend-master
          npm install 
          npm install -g jsdoc
          jsdoc -c jsdoc.json
          npm run docs
          npm run build 
     
  Build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Sign in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}} 
      - name: Deleting old Images 
        run: docker rmi -f $(docker images -q)
      - name: Build Docker Images
        run: |
         cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-frontend-master
         docker build -t wwag3/wednesdaywickedadventures:latest . 
      - name: Publish Image to docker Hub
        run: docker push wwag3/wednesdaywickedadventures:latest

  Pulling_docker_image:
    runs-on: self-hosted
    needs: Build_docker_image
   # runs-on: self-hosted
    steps:
      - name: pulling image from docker hub 
        run: sudo docker pull wwag3/wednesdaywickedadventures:latest

      - name: Deleting old contanier 
        run: sudo docker rm -f wwafrontendapp

      - name: building container
        run: sudo docker run --name wwafrontendapp -p 3000:3000 -d docker pull wwag3/wednesdaywickedadventures:latest

      - name: Deleting old contanier 
        run: sudo docker rm -f wwabackend

      - name: building docker backend
        run: sudo docker run --name wwabackend -p 5000:5000 -d pavanvarikolu/wwabackend:v1.1.1




   